version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: deskflow-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: deskflow_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - deskflow_pgdata:/var/lib/postgresql/data

volumes:
  deskflow_pgdata:
